### ISSUE TITLE
Error: Unable to access jarfile /app/pickaxe-scans-2.3-SNAPSHOT.jar

### ISSUE THREAD

**Issue by tzeappa** [Netcentric/pickaxe-security-scanner#26]
When trying to run the container with the documented commands I'm receiving the following:

`docker run --rm -it -v /Users/my_user/Downloads/scan-output:/app/output ghcr.io/netcentric/pickaxe-security-scanner:latest --url https://www.my-website.com/`
`--url https://www.my-website.com/`
`Running Scanner`
`Error: Unable to access jarfile /app/pickaxe-scans-2.3-SNAPSHOT.jar`

Thanks

**Comment by thomashartm** [comment]
Ok thank you I will pick that up.

**Comment by thomashartm** [comment]
Pushed a fixed which is
